config/routes.rb
Thinventions::Application.routes.draw do
  
  resources :projects

  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "static_pages/learn"
  get "static_pages/make"
  get "static_pages/about"
  root "static_pages#learn"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  attr_accessible :user_id, :name, :desc
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :name

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize
  
  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, alert: "Please log in"
    end
  end
  
  def signed_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end
  
  helper_method :signed_in?
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(user_id: session[:user_id])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :desc)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  def new
  end

def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In!"
      redirect_to root_path
    else
      flash[:error] = 'Invalid username or password.'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authorize
  
  def learn
  end

  def make
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flashmsg flash_#{name}"

app/views/layouts/_navigation.html.haml
%div.center#circleBox
  .circle.greenBack
  .circle.darkBlueBack
  .circle.sunflowerBack
  .circle.salmonBack

%div.nav.collapsed#menu_bar
  %a#menu-icon
    &#9776;
  =link_to "home", root_path
  -if signed_in?
    =link_to "projects", projects_path
    =link_to "logout", logout_path, method: :delete
  -else
    =link_to "login", login_path
    =link_to "signup", new_user_path
  =link_to "browse", root_path
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Thinventions'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Thinventions'}"}
    %link{:href=>'http://fonts.googleapis.com/css?family=Raleway:500|Pacifico', :rel=>"stylesheet", :type=> 'text/css'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

    .logo#logoBottom="thinventions.com"

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, "Name your awesome project!"
    = f.text_field :name
  .field
    = f.label :desc, "Describe your project!"
    = f.text_area :desc
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
.page-background.sunflowerBack
  .login-box
    %h1 Editing project

    = render 'form'

    = link_to 'Show', @project
    \|
    = link_to 'Back', projects_path

app/views/projects/index.html.haml
.page-background.sunflowerBack
  .login-box
    %h1 Your Projects

    %table.table.table-striped
      %tr
        %th Name
        %th Desc
        %th
        %th
        %th

      - @projects.each do |project|
        %tr
          %td= project.name
          %td= project.desc
          %td= link_to 'Show', project, :class=>"button"
          %td= link_to 'Edit', edit_project_path(project)
          %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Project', new_project_path

app/views/projects/new.html.haml
.page-background.sunflowerBack
  .login-box
    %h1 New project

    = render 'form'

    = link_to 'Back', projects_path

app/views/projects/show.html.haml
.page-background.sunflowerBack
  .login-box
    %p#notice= notice

    %p
      %b Name:
      = @project.name
    %p
      %b User:
      = @project.user_id
    %p
      %b Desc:
      = @project.desc

    = link_to 'Edit', edit_project_path(@project)
    \|
    = link_to 'Back', projects_path

app/views/static_pages/about.html.haml
%h1 StaticPages#about
%p Find me in app/views/static_pages/about.html.haml

app/views/static_pages/learn.html.haml
.first-learn-panel
  This is the 
  %span.gray-boldness="leanest" 
  way to 
  %br
  Bring your tech ideas to life.
  %br
  %br
  %span.gray-aside
    < no coding knowledge necessary />
  %br
  =image_tag("down_arrow.png", class:"learn-down-arrow")

.learn-panel
  =image_tag("Toby.png", class:"toby-learn")
  %br
  Hi! My name is Toby.
  %br
  I'll be coding your application as you we chat.
  %br
  %br
  =link_to "Sign up and start thinventing", new_user_path, class:"learn-link"

app/views/static_pages/make.html.haml
%h1 StaticPages#make
%p Find me in app/views/static_pages/make.html.haml

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  .actions
    = f.submit 'Sign up'

app/views/users/edit.html.haml
.page-background.login-background
  .login-box
    %h1 Edit your profile

    = render 'form'

    = link_to 'Show', @user
    \|
    = link_to 'Back', users_path

app/views/users/index.html.haml
.page-background.login-background
  %h1 Listing users

  %table
    %tr
      %th Name
      %th Password
      %th
      %th
      %th

    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New User', new_user_path

app/views/users/new.html.haml
.page-background.login-background
  .login-box
    %h1 Signup & Thinvent!

    = render 'form'

    = link_to 'Cancel', root_path

app/views/users/show.html.haml
.page-background.login-background
  .login-box
    %p#notice= notice

    %p
      %b Name:
      = @user.name

    = link_to 'Edit', edit_user_path(@user)
    \|
    = link_to 'Back', root_path